services:
  - type: web
    name: task-manager
    runtime: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        sync: false
    disk:
      name: app-instance
      mountPath: instance
      sizeGB: 1




